### ISSUE TITLE
Maybe redux getting zapped; empty interface on startup until node start

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1083]
In this case, I caught it without the node being able to start, so my app had no memory. Strange though because I'm clearly onboarded...

![IMG_3318](https://user-images.githubusercontent.com/370259/58193049-ffbbe580-7c76-11e9-840f-ff1f37e0f288.JPG)
![IMG_3319](https://user-images.githubusercontent.com/370259/58193050-ffbbe580-7c76-11e9-9abf-4773c2f2f027.JPG)
![IMG_3320](https://user-images.githubusercontent.com/370259/58193051-00547c00-7c77-11e9-90dc-9a08ae628d5a.JPG)
![IMG_3321](https://user-images.githubusercontent.com/370259/58193052-00547c00-7c77-11e9-9b4e-ac4be6ba37ea.JPG)

**Comment by andrewxhill** [comment]
this issue is really noticeable for me. anytime i open the app after it has been closed for a while, my app is completely empty (pictures above) and seems to repopulate. 

I know this wasn't the case just a couple weeks ago because I did a lot of work to ensure that avatars on the group page weren't loading anew very often (you see a lot less jumping around of avatars in those rows). However, you don't notice that work now because the whole thing has to reload from scratch. 

i looked at the whitelist history and didn't see any significant change to something we are storing. what else could be causing this?

**Comment by asutula** [comment]
Can you toggle on the verbose UI so you can see how the timing of the UI populating is related to the node state?

It is true that no UI is rendered until the node _starts_, but if the UI (even empty UI) is displayed at all, the node should at least be started. If there is a lag after that, it would be caused by some other slowness. Maybe getting data from the node? Will have to dig in more.

**Comment by andrewxhill** [comment]
this is all getting solved elsewhere. issue is about node start timing etc
