### ISSUE TITLE
Contact multi-select > New group

### ISSUE THREAD

**Issue by asutula** [textileio/photos#1110]
You should be able to multi-select some contacts and start a new group with them. Maybe there is an option of whether it should be an open or closed group.

**Comment by undercase** [comment]
Working on this today. Since there's no longer a `+` button for the AddContact modal in the upper righthand corner, I'll put a button there to trigger the multi-select UI. It will animate in checkboxes next to each contact on the right hand side, which the user can toggle by pressing on the contact. It will also animate in a button fixed to the bottom of the screen to finish creating the group. When the multi-select UI is active, the top right button will function as a Cancel button. Once the user is done, a modal will pop up with a form to select the group name and choose whether it is open or closed. Once they submit this form, they will be brought to the new group.

**Comment by undercase** [comment]
I have the UI logic for multi-select working beautifully, now I need to add logic to actually create a group. Should it be as simple as making a new thread and then sending an invite to everyone selected, or is there more logic required for this?

**Comment by undercase** [comment]
E.g. creating a new thread, using `ThreadActions.addInternalInvitesRequest`, and then navigating to it?

**Comment by asutula** [comment]
I think that should do it. @sanderpick might have some more thoughts on the invite sending.

If you use the existing create group screen like you mentioned to me you would, one cool thing about adding list of contacts as a prop there, is that it opens the door to editing that list on that screen which means we could implement a flow where you simultaneously create a new group and add participants to it.

**Comment by asutula** [comment]
Instagram has basically blueprinted all these flows

**Comment by undercase** [comment]
At the same time that I add the list of contacts as a prop to the existing create group screen, I can reuse the existing `ThreadEditFriends` component there to kill two birds with one stone.

**Comment by undercase** [comment]
Plus that component already includes logic for sending multiple invites at once.

**Comment by undercase** [comment]
Got this feature working great by adding the contacts prop to `CreateThreadModal`, if you want to take a look at my code in `thomas/contactMultiSelect`. Now to work on styling (barebones right now) and extending the modal to have a picker like instagram.

**Comment by asutula** [comment]
Let's save the contact picker in the modal for later. It's a different feature.
