### ISSUE TITLE
Add cafes to settings

### ISSUE THREAD

**Issue by undercase** [textileio/photos#1165]
View cafes and register/de-register in the settings screen.

**Comment by undercase** [comment]
Here is the Cafes list screen, which should be accessible through the settings:

![Cafes Settings Screen](https://user-images.githubusercontent.com/2547706/59542618-d8061900-8ed4-11e9-9e98-1401433ce862.png)

We can use [react-native-swipe-list-view](https://github.com/jemise111/react-native-swipe-list-view) to support the swipe to show the deregister button functionality. As you'll see in the mockup of the individual cafe screen, users may also deregister from there. The "Register With a New Cafe" button lets the user register with a new cafe by peer id. Deregistering from your last cafe will open a modal for confirmation.

**Comment by asutula** [comment]
@sanderpick and I were talking last weekend about the architecture of cafes and how they relate to the UX. Maybe you guys talked since then and maybe what I know is out of date, but my understanding is that we can generally think about cafe management in terms of a single cafe, or possibly choosing one cafe per "service" (backup, inboxing, push notifications, etc). So, my point is, don't design these screens around managing  multiple cafes.

**Comment by undercase** [comment]
So something more like “This is your cafe” rather than “these are your cafes”?

**Comment by sanderpick** [comment]
Oh, we still want the notion of multiple. You might have one cafe for storage, another for notifications, another for another service, etc... It's just that in our current state everyone will get the existing services through one because we don't yet have the concept of a service. On a more practical note, we need to display a list so that existing users can de-register one of the duplicates (i.e, no need to have two that both do storage). 

Ideally, there'a a "+" button in the upper right where you can add an additional. This would be used by existing users to register with the new cafes (when they land).

**Comment by undercase** [comment]
Okay, solid.

**Comment by undercase** [comment]
So, still include the ability to display multiple cafes (even if it won't be used right now) and turn the new cafe button into a plus icon in the upper right corner. Does that sound good?

**Comment by sanderpick** [comment]
Yeah sounds good. The multiple _will_ be used though... all our users have two cafes registered

**Comment by undercase** [comment]
Okay, awesome. So just move the new cafe button to the top right, but still display multiple. Sounds good.

**Comment by undercase** [comment]
Here's what the individual cafe screen ended up looking like, since I didn't post a mockup:

![image](https://user-images.githubusercontent.com/2547706/60041632-e816b900-9689-11e9-8083-4bc32f4f16a9.png)

In the future, once services are implemented, users will be able to tap on each one to toggle whether the cafe is doing it.

**Comment by sanderpick** [comment]
Very cool

**Comment by undercase** [comment]
The register w/ a new cafe UI looks like this:

![image](https://user-images.githubusercontent.com/2547706/60051699-8c582a00-96a1-11e9-9fcc-1fb2c93bf9ce.png)

The onboarding screen uses the same list component. It supports filtering out cafes the user is already registered with.

**Comment by undercase** [comment]
There is also a search icon in the top right that wasn’t added yet when I took that screenshot.

**Comment by sanderpick** [comment]
💥
