### ISSUE TITLE
UI crash when de-registering cafe

### ISSUE THREAD

**Issue by asutula** [textileio/photos#1264]
De-register, get the black screen

https://fabric.io/we-are-set-inc/ios/apps/io.textile.wallet.beta/issues/4b011b164ce92f9b11d4bcd3ed9cb67d

**Comment by undercase** [comment]
Hmm, investigating this.

**Comment by sanderpick** [comment]
I've seen this a couple time - ios and android

**Comment by andrewxhill** [comment]
i hit it in my work yesterday and thought it was a quick fix, it wasn't so i kept focused on my current branch.

what it looks like,

1. there is an on success callback coming from the UI when deregistering. 
2. after dereg success, that callback should take the user to a UI where the cafe isn't expected anymore (because it wont exist)
3. either tha callback doesn't fire or it fires too slow (after an attempt to redraw the screen that requires the cafe details that no longer exist)
