### ISSUE TITLE
"Leave thread" when it's one you created is confusing

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#432]
Not common in centralized architectures,  "what happens, is it deleted". We should just clarify the first time perhaps

**Comment by carsonfarmer** [comment]
Do we currently have a way to tell if a thread is one you've joined versus one you've created?

**Comment by carsonfarmer** [comment]
Turns out no, we don't really distinguish between a thread a client has created versus one they've joined. Based on a discussion with @sanderpick, one proposal here would be to show a popup or overlay of some kind the first time someone leaves a thread, with something along the lines of:

"Sorry to see you go. If you this is a thread you created, it will continue to exist after you've left. That means, you can come back any time you like!" or similar.

**Comment by andrewxhill** [comment]
should be better now
