### ISSUE TITLE
Resurrect camera roll backup processing code

### ISSUE THREAD

**Issue by asutula** [textileio/photos#945]

**Comment by asutula** [comment]
@sander, I know we’ve probably been through this before, but need to bring it up again now that we're implementing photo "backup" as a feature in the app.

Photo "backup" seems straight forward... we need to make sure the files are added to the local node and remotely pinned. In this case, backed up photos can also be used as the source for a photo shared to other groups/threads.

We used to talk about a "auto pin" feature where user's photos would be pinned locally, but not remotely pinned. I guess the use case was for syncing to other account peers like a desktop app. Do we still want to provide that feature?

If we do still want to support auto pin (no remote pin), I'm wondering how that interacts with sharing auto pinned files to other groups/threads. It seems like the content wouldn't be discoverable to other peers. 

In that case, do we not show a "share" option for files that are only auto pinned locally? 

If we need to choose whether or not to show a "share" option depending on if a file has been remotely pinned or not, where do we get that state from? Can the Textile node provide that information? Does the app need to keep track of that state on it's own?

**Comment by asutula** [comment]
@andrewxhill would love your input on the above as well as I remember you being a bit auto-pin proponent ;)

**Comment by sanderpick** [comment]
I feel like this could be an enhancement. On the other hand, maybe pinning locally and then using go-textile as the queue mechanism is actually a better workflow. In which case we could show icons for the remote pin(s). Let's talk through it tomorrow?

**Comment by andrewxhill** [comment]
right yeah... don't mind the order of operations here, whatever makes sense. the two considerations I think I was including in thinking about that,

1. Is the open source app useful at all, without a cafe. Seems like it may have moved a bit further away from that, but perhaps with desktop peers we'll get back there.
2. What is it going to cost to store all camera rolls... this feature could turn our network from "each new user adds value" to "each new users costs money". What limits/quotas are possible, what happens when someone reaches those, etc. But let's experiment first, this isn't something to get too worried about yet. 

So whatever development order makes sense at this point.

**Comment by asutula** [comment]
Ok thanks for in the input. Let's definitely talk today about it @sanderpick

**Comment by sanderpick** [comment]
Re: open source, https://github.com/textileio/go-textile/issues/566 will help massively.

Actually, the more I think about it, the more the "local pin first" approach make sense. Seems like a faster dev apporach. I'm also thinking about how I use Dropbox for photos... I have it set to not backup over cell data or even wifi, I just plug it in and it syncs. With textile, I could see a plug-in event triggering a sync (over wifi perhaps) to a desktop node, which in turn hits a cafe or two. Anyway, lots to talk about

**Comment by asutula** [comment]
Ok, I got all the existing camera roll related code rebased and merged into master, so considering this done. Any additional work is being tracked by new issues.
